### ISSUE TITLE
the function of gt_bboxes_2d_to_3d 

### ISSUE THREAD

**Issue by Yzichen** [tusen-ai/MV2D#4]
https://github.com/tusen-ai/MV2D/blob/429863f2ceb1ece6a71ba1f2be7d0300b745da28/mmdet3d_plugin/models/detectors/mv2d.py#L169-L175

I noticed that during the model forward_train, gt_bboxes_2d_to_3d is only used in the above code. 
In addition, neither gt_boxxes_3d nor gt_labels_3d are subsequently used here, what is their function?

**Comment by wangzt-halo** [comment]
They are only used for debug, you can ignore these params.
